version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 5
    reviewers:
      - waki285
    assignees:
      - waki285
    commit-message:
      prefix: "ğŸ—ƒ chore"
      prefix-development: "ğŸ—ƒ chore"
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 5
    reviewers:
      - waki285
    assignees:
      - waki285
    commit-message:
      prefix: "ğŸ› fix"
      prefix-development: "ğŸ› fix"
      include: scope
